apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment-01
  name: nginx-deployment-01
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx-deployment-01
  template:
    metadata:
      labels:
        app: nginx-deployment-01
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapp
spec:
  selector:
    app: nginx-deployment-01
  ports:
  - port: 80
    targetPort: 80
