apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deployment-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-pod
    spec:
      containers:
      - image: sudheer10thota\webapp:1.0.0
        name: webapp
        ports:
        - containerPort: 8090
---
apiVersion: apps/v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  selector:
    app: deployment-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
