kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deployment-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-pod
    spec:
      containers:
      - image: sudheer10thota/webapp:${DOCKER_TAG}
        name: webapp
        ports:
        - containerPort: 8090
---
kind: Service
apiVersion: v1
metadata:
  name: webapp
spec:
  type: LoadBalancer
  selector:
    app: deployment-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
