apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: sudheer10thota\webapp:tagVersion
      ports:
        - containerPort: 9080
---
apiVersion: apps/v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
  type: LoadBalancer   
